"""Task b1: Generate the complete Fiverr gig package."""
from ._common import write

PACKAGE = """# Fiverr Gig Package — AI Services
*Generated by the GTM Agent. Copy-paste into Fiverr.*

---

## PROFILE BIO (paste into Fiverr profile)
```
AI automation engineer specializing in Arabic-language AI agents, WhatsApp chatbots, and voice assistants for businesses in the GCC.

I've built AI systems for real estate, hospitality, and services industries — agents that handle customer inquiries, qualify leads, and schedule appointments automatically.

Services:
• WhatsApp AI chatbots (Arabic + English)
• Voice AI agents for customer calls
• AI workflow automation (n8n, Make.com)
• Custom LLM integrations

Based in Oman. Native Arabic speaker. Available for GCC clients.
```

---

## GIG TITLE (exact)
```
I will build an Arabic AI chatbot for your WhatsApp Business
```

---

## GIG DESCRIPTION (paste into Fiverr)
```
Is your business missing leads because you can't reply to WhatsApp messages fast enough?

I build intelligent Arabic AI chatbots that handle your WhatsApp inquiries 24/7 — answering questions, collecting customer details, and routing hot leads to your team instantly.

✅ WHAT YOU GET:
• Custom AI trained on your business/products
• Arabic + English support (Khaleeji dialect available)
• Automatic lead qualification
• Appointment booking integration
• WhatsApp Business API or Meta integration
• 7-day delivery

✅ PERFECT FOR:
• Real estate agencies
• Hotels and hospitality
• Retail and e-commerce
• Healthcare clinics
• Any GCC business with Arabic customers

I've built AI agents handling thousands of conversations per month. Your chatbot will sound like a professional team member — not a robot.

📦 PACKAGES:
Basic ($50): Single-purpose bot (FAQ or lead capture)
Standard ($100): Full customer service bot with lead capture + routing
Premium ($200): Full AI agent with CRM integration, voice notes, multilingual

Message me before ordering if you have specific requirements.
```

---

## GIG TAGS (add all)
```
whatsapp chatbot, arabic chatbot, ai agent, chatbot development, whatsapp automation, arabic ai, gcc chatbot, lead generation bot, business automation, ai chatbot
```

---

## FAQ (paste into gig FAQ section)
**Q: Do you speak Arabic?**
A: Yes! Native Arabic speaker (Omani). Your chatbot will speak natural Khaleeji Arabic, plus Modern Standard Arabic and English.

**Q: How long does delivery take?**
A: Basic 3 days, Standard 5 days, Premium 7 days. Rush delivery available on request.

**Q: Which platform does the bot run on?**
A: WhatsApp Business API (Meta) — the official, reliable way. I handle the whole setup.

**Q: Can you train it on my specific business?**
A: Yes — I train it on your products, services, FAQs, and tone. You send me your info, I do the rest.

---

## PRICING
| Tier | Price | Includes |
|------|-------|----------|
| Basic | $50 | Single-purpose bot (FAQ or lead capture) |
| Standard | $100 | Full customer service bot + lead capture + routing |
| Premium | $200 | Full AI agent + CRM integration + voice notes + multilingual |
"""


def run(ctx):
    p = write(ctx, "fiverr/gig-package.md", PACKAGE)
    return {"summary": "Fiverr package: bio, title, description, tags, FAQ, pricing", "out": "assets/fiverr/gig-package.md"}
