"""Task a6: Generate the client onboarding brief (what to build for the paying client)."""
from ._common import write

BRIEF = """# Murshed Client Onboarding Brief
*Generated by freebuff-agents. Use after the client pays.*

## Client: [AGENCY NAME] — [CONTACT] — [DATE PAID: OMR 50]

---

## 1. COLLECT FROM CLIENT (day 1)
1. Agency logo + brand colors
2. Property list (photos, prices, areas, links)
3. Common WhatsApp questions (paste 10-20 real ones)
4. Opening hours + who receives hot leads
5. Preferred tone (formal / friendly / khaleeji)

## 2. WHAT MURSHED DOES FOR THEM
- Replies to property inquiries instantly (24/7) from their knowledge base
- Asks qualifying questions: budget, area, purpose, timeline
- Books viewings via calendar link
- Sends property details + photos automatically
- Follows up after 1 and 3 days
- Escalates hot leads to the human agent
- Weekly report: conversations, qualified leads

## 3. BUILD STACK (90% done in ~/oman-lead-bot)
- Backend: Convex (deployed)
- WhatsApp: Meta Business Cloud API (number registered)
- LLM: Groq/Gemini free tier (wired)
- Admin: oman-lead-bot dashboard

## 4. DELIVERY CHECKLIST (7 days)
- [ ] Day 1: collect client info
- [ ] Day 2-3: load properties + FAQs
- [ ] Day 4: train tone + test 20 conversations
- [ ] Day 5: connect client's number (or test number)
- [ ] Day 6: client test drive — fix flags
- [ ] Day 7: handover + training (15 min) + invoice month 2

## 5. MONTH 2 BILLING
- Remind 3 days early: "شهركم الثاني — تجديد ب 50 ريال؟"
- Offer: 3 months upfront → 1 month free
"""


def run(ctx):
    p = write(ctx, "outreach/client-brief.md", BRIEF)
    return {"summary": "Client onboarding brief ready (collection list, stack, 7-day checklist)", "out": "assets/outreach/client-brief.md"}
