"""Task d2: Generate the Murshed product demo script for client calls."""
from ._common import write

DEMO = """# Murshed — Live Product Demo Script (for client calls)
*Generated by freebuff-agents. Replaces the 'concept-only' pitch once oman-lead-bot is wired.*

## Prereqs before demoing
- [ ] WHATSAPP_TOKEN + WHATSAPP_PHONE_NUMBER_ID pasted in oman-lead-bot Settings → Keys
- [ ] Webhook configured (`<site-url>/whatsapp-webhook` with WHATSAPP_VERIFY_TOKEN)
- [ ] Test number can message you (or use the sandbox number)

## Demo flow (8 minutes, live)

**1. Set the stage (30s)**
"هذا ديمو حي — مش عرض شرائح. أنا بكتب رسالة كأني عميل، وبتشوفون الرد خلال ثواني."

**2. Live test 1 — property question (2 min)**
Send: "كم سعر شقة بغرفتين في الموج؟"
Expect: Murshed answers from knowledge base with price + area + link.
Say: "لاحظوا: الرد فوري، باللهجة المحلية، والمعلومة من قاعدة بياناتكم مو من الجو."

**3. Live test 2 — qualification (2 min)**
Send: "أبي شي قريب من المدارس، ميزانيتي 150 ألف، أدفع كاش."
Expect: Murshed asks budget/area/timeline, qualifies.
Say: "هني ميزة التأهيل — بدل ما يضيع وقت الموظف مع كل استفسار، يصلك العميل الجاهز."

**4. Live test 3 — booking (2 min)**
Send: "تمام، أبي أزور يوم الخميس."
Expect: Murshed offers a calendar slot.
Say: "وهني الموعد محجوز تلقائيًا في تقويم فريقكم."

**5. Close (1.5 min)**
"التكلفة 50 ريال شهريًا — أقل من موظف استقبال ليوم واحد. الشهر الأول ضمان استرداد كامل.
أبي أبدأ معكم هذا الأسبوع — إيداع 25 ريال يحجز التطوير."

## If they ask about numbers/ROI
"بدل ما نخمّن: نجرب أسبوعين على رقم تجريبي. كل عميل يرد عليه مرشد خلال ثواني بدل ساعات —
احسبوا كم صفقة تضيع حاليًا بسبب التأخير."

## Objection redirects
For any objection (price, trust, staff, time): validate → one concrete answer → redirect to the live demo link.
Full scripts in assets/murshed/objections.md
"""


def run(ctx):
    p = write(ctx, "murshed/demo.md", DEMO)
    return {"summary": "Product demo script ready (3 live tests + close)", "out": "assets/murshed/demo.md"}
